<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Title>WinterRose.TaskLock</Title>
        <Version>26.3.0</Version>
        <Authors>TheSnowOwl</Authors>
        <Company>WinterRose</Company>
        <Description>A small library that deduplicates a task request based on a key. and optionally caches the result for a while</Description>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
    </PropertyGroup>

    <ItemGroup>
      <None Include="..\LICENSE">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>

</Project>
